### ISSUE TITLE
Problem with mobile screens

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#1]
- Pay with bitcoin not visible on mobile screen

https://www.prestashop.com/forums/topic/570036-free-modulebitcoin-payments-blockonomics/

**Comment by blockonomics** [comment]
![post-1347358-0-44649300-1481108932_thumb](https://cloud.githubusercontent.com/assets/22165583/20999853/73ec8636-bd3d-11e6-8553-ab63e3bc0b11.png)

**Comment by shivaenigma** [comment]
Cannot reproduce
