### ISSUE TITLE
Resetting or uninstalling module deletes `ps_blockonomics_bitcoin_orders` in DB

### ISSUE THREAD

**Issue by cnohall** [blockonomics/prestashop-plugin#103]
When resetting the module or if uninstalling it, `ps_blockonomics_bitcoin_orders` in the db is deleted. We probably want to keep the table in the database even if the user decides to uninstall or reset the module. 

When trying to look old orders in the admin page I get this error message (due to the data being removed).

![image](https://user-images.githubusercontent.com/36883813/114305213-104b0280-9b12-11eb-8c16-fb7c8b01707f.png)

I'll do some more testing to make sure that it is not just a problem on my end.

**Comment by shivaenigma** [comment]
>We probably want to keep the table in the database even if the user decides to uninstall or reset the module

This is expected behaviour. The module should remove all associated data when it gets deleted.

However, the order details should still work in admin. Can you find out what  it causing it to give this error

**Comment by cnohall** [comment]
Yes, it seems like we have encountered a similar error before, and other modules have experienced similar disruptions. First I thought it was because we're dropping the table `ps_blockonomics_bitcoin_orders`. However, it doesn't seem to be that simple.  I'll investigate it further.

**Comment by cnohall** [comment]
A quick fix is to comment out the following lines in the PrestaShop code:
https://github.com/PrestaShop/PrestaShop/blob/develop/src/Adapter/Order/QueryHandler/GetOrderForViewingHandler.php#L341-L352

I'll see if it's possible to adapt the module in such a way that this doesn't happen after removing it. It might be a problem native to PrestaShop. I'll see what we can do.

**Comment by shivaenigma** [comment]
Closing in favour of discussion in #102. Tables should still be deleted.
