### ISSUE TITLE
Bitcoin image missing on checkout - Pay by bitcoin

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#111]
<img width="649" alt="60805381b21b8" src="https://user-images.githubusercontent.com/22165583/116865376-233f8700-ac27-11eb-9cba-a5577741fc34.png">

**Comment by cnohall** [comment]
Which version of PrestaShop and the module is being used?

**Comment by blockonomics** [comment]
Using our module 1.7.91 . Prestashop version will confirm. Looks like we don't have image set in code anyway right ?

**Comment by cnohall** [comment]
True, I think it's because the stock/native payment options don't have an image set.

![image](https://user-images.githubusercontent.com/36883813/117084934-6d3d7f80-ad83-11eb-966d-ce14cfcccd6c.png)

I'll examine how we can add an image in a visually pleasing way.

**Comment by cnohall** [comment]
There's a file called `payment-selection-logo.png` in the `views/img` folder. It seems to be a legacy image, since it's not used anywhere in the code. I tested setting it as the payment option logo through using `->setLogo(imagepath)`. However, it doesn't look that good. 

![image](https://user-images.githubusercontent.com/36883813/117094248-42145980-ad9e-11eb-8405-4dc030d4753d.png)

We could try making it smaller, perhaps it looks better that way. Feel free to mention any other suggestions.

**Comment by blockonomics** [comment]
> We could try making the image smaller, perhaps it looks better that way. Feel free to mention any other suggestions.

Yes lets try a better look image with the correct size. Simple idea is to look at images of other modules and follow same size/format

**Comment by cnohall** [comment]
I've done some further research. The position of the text and image seem to vary depending on the version of PrestaShop.

![image](https://user-images.githubusercontent.com/36883813/117106223-74cc4b00-adba-11eb-88fd-37d33e66c69a.png)
### Explination of the different colored windows
**Green**: Our current version of the image. When comparing to other modules the size and format looks quite good. Perhaps a slightly different color could be considered? I'm thinking perhaps the same green as in the Blockonomics logo?
**Dark Blue**: Paypal
**Light Blue**: I noticed a very nifty thing with the Paypal payment option. They had a small blue information icon, that looks like (i). When hovering over the icon a new window appears with some information about their service. I think it gives a professional impression and creates confidence in the product. Perhaps something for us to consider. 
**Orange**: Skrill payment module

**Comment by blockonomics** [comment]
It would be useful to use the same image accross module. We could use a resized version of https://github.com/blockonomics/woocommerce-plugin/blob/master/img/bitcoin-icon.png

>  I noticed a very nifty thing with the Paypal payment option. They had a small blue information icon, that looks like (i). When hovering over the icon a new window appears with some information about their service. I think it gives a professional impression and creates confidence in the product. Perhaps something for us to consider.

Yes definitely, would be very useful and we could think about this in the future
