### ISSUE TITLE
504 error after clicking order with obligation to pay

### ISSUE THREAD

**Issue by dialt0n3** [blockonomics/prestashop-plugin#114]
since new update when customer clicks order it just gives a 504 ERROR

please help

**Comment by cnohall** [comment]
Hello,

We're ready and willing to help. Is it when he clicks the order information, the invoice, or when he wants to pay?

**Comment by dialt0n3** [comment]
related to https://github.com/blockonomics/prestashop-plugin/pull/115

reverted to older version to correct issue.

**Comment by DarrenWestwood** [comment]
In some cases `getInvoicesCollection()[0]` leads to 504 error during the checkout.
Reverting this code to [update the invoice directly in the database](https://github.com/blockonomics/prestashop-plugin/pull/131/files) works in these cases, however it will be best to use Prestashop functions to perform this.

The correct usage appears to be `getInvoicesCollection()->getFirst()`, which may relate to this issue. Lets try and replicate the error and fix this behavior.
