### ISSUE TITLE
 Payment address and info no longer visible in back office

### ISSUE THREAD

**Issue by dialt0n3** [blockonomics/prestashop-plugin#116]
Since update to Prestashop 1.7.7.x Payment address and info as show below is no longer visible in order details in back office

https://github.com/blockonomics/prestashop-plugin/raw/master/views/img/screenshot-1.png

**Comment by cnohall** [comment]
Hello @dialt0n3,

Thanks for getting in touch! Our team is looking into finding a solution to this issue on your website.

**Comment by DarrenWestwood** [comment]
Closing this issue as https://github.com/blockonomics/prestashop-plugin/pull/107 displays the bitcoin transaction id of the payment in the Prestashop Payment section
![PS Payment Info](https://user-images.githubusercontent.com/39666372/140042245-9e1df323-75ed-43f5-adf3-a74f7b5b7dcf.png)
and the payment address is visible in the pdf invoice.
![PDF invoice](https://user-images.githubusercontent.com/39666372/140043693-31e5d8c8-80be-42aa-a036-5b5b4615736c.png)
