### ISSUE TITLE
Doesnt show in Prestashop 1.6

### ISSUE THREAD

**Issue by cryptojake** [blockonomics/prestashop-plugin#13]
Hello! Just installed the module, but it doesnt show on the module list in prestashop 1.6... Anything I can do to see this? after uploading the zip it said it installed successfully. Thanks for any help!

**Comment by shivaenigma** [comment]
Hi @cryptojake our module is tested on 1.6 and should wok.  Have you uploaded the release zip and not the source. 
https://github.com/blockonomics/prestashop-plugin/releases/download/1.0.11/blockonomics.zip
https://github.com/blockonomics/prestashop-plugin/releases
-

**Comment by cryptojake** [comment]
That was it, my mistake. Thank you!

**Comment by shivaenigma** [comment]
No problem. Will update README to make it more clear.
