### ISSUE TITLE
Responsive crypto select buttons

### ISSUE THREAD

**Issue by DarrenWestwood** [blockonomics/prestashop-plugin#133]
The buttons on the select crypto page require updating to use the new vertical design, which uses the `<button>` tag instead of a table.
The woocommerce plugin can be used as a reference: https://github.com/blockonomics/woocommerce-plugin/pull/254
Instead of `class="woocommerce-button"`, [bootstrap classes](woocommerce-button) can be used as we are currently importing the [bootstrap prestashop ui kit](https://github.com/blockonomics/prestashop-plugin/blob/master/controllers/front/validation.php#L42)

**Comment by thisisayush** [comment]
PR Raised
