### ISSUE TITLE
Add advanced settings

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#146]
Add advanced settings from wordpress. We should atleast have this
- Underpayment slack
- Time of countdown

**Comment by ankit61d** [comment]
Sure. I'll take a look.

**Comment by blockonomics** [comment]
@ankit61d  Here is the todo for you:
1. Setup a prestashop store locally and install our [plugin](https://github.com/blockonomics/prestashop-plugin/)
2. Add code in module settings to add the two advanced settings I mentioned above
3. Code snippets and working can be copied from our [wordpress plugin](github.com/blockonomics/woocommerce-plugin)
