### ISSUE TITLE
Return To Orders History After Payment?

### ISSUE THREAD

**Issue by cryptojake** [blockonomics/prestashop-plugin#15]
So far everything works great!

Is it possible to return to the order history after a payment is made? It would be ideal if this happened as soon as the transaction appears on the blockchain (zero confirms). This way the buyer knows the payment was received, even if it is still waiting to confirm.

Thank you!

**Comment by shivaenigma** [comment]
Good suggestion. I will see what other payment gateways are doing. Right now the user should see https://medias3.prestastore.com/817111-pbig/blockonomics-bitcoin-payments.jpg on zero confirmation.  The Status would change to Confirmed after 2 confirmations.

**Comment by cryptojake** [comment]
Actually, your page is the best option, but the information on that page never changes to confirmed with my module for some reason.

**Comment by blockonomics** [comment]
Closing this in favour of #16
