### ISSUE TITLE
[PrestaShop v8] Checkout is not working

### ISSUE THREAD

**Issue by ankit61d** [blockonomics/prestashop-plugin#157]
PS v8 is [officially available](https://build.prestashop-project.org/news/prestashop-8-0-0-available/). 
Checkout & Test Setup is not working with our latest plugin (v1.7.96).
![ps_v8_checkout_error](https://user-images.githubusercontent.com/97018228/208161310-ae26951d-12dc-4421-8c6d-f2199480dd44.gif)

Checkout Error Log:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Tools::jsonDecode() in C:\xampp\htdocs\prestashopv8\modules\blockonomics\blockonomics.php:300
Stack trace:
#0 C:\xampp\htdocs\prestashopv8\modules\blockonomics\blockonomics.php(255): Blockonomics->doCurlCall('https://www.blo...')
#1 C:\xampp\htdocs\prestashopv8\modules\blockonomics\controllers\front\payment.php(331): Blockonomics->getPrice('btc', 1)
#2 C:\xampp\htdocs\prestashopv8\modules\blockonomics\controllers\front\payment.php(117): BlockonomicsPaymentModuleFrontController->getBits(Object(Blockonomics), 'btc', Object(Currency), 47.25)
#3 C:\xampp\htdocs\prestashopv8\classes\controller\Controller.php(308): BlockonomicsPaymentModuleFrontController->postProcess()
#4 C:\xampp\htdocs\prestashopv8\classes\Dispatcher.php(503): ControllerCore->run()
#5 C:\xampp\htdocs\prestashopv8\index.php(28): DispatcherCore->dispatch()
#6 {main}
  thrown in C:\xampp\htdocs\prestashopv8\modules\blockonomics\blockonomics.php on line 300
```
Full testing sheet here ➡ https://docs.google.com/spreadsheets/d/1O3XqNhLElVpWXcMetFUl_AlEHpThWTpx9bvVPRedrgg/edit?usp=sharing

**Comment by anktd** [comment]
As per [changelog](https://devdocs.prestashop-project.org/8/modules/core-updates/8.0/#removed-methods) , `Tools::jsonDecode()` deprecated in 1.7.0

Using [`json_decode`](https://www.php.net/manual/en/function.json-decode.php) [here](https://github.com/blockonomics/prestashop-plugin/blob/1.7/blockonomics.php#L300) resolves the issue and checkout works fine.
<img width="818" alt="chrome_N8TfflVCpS" src="https://user-images.githubusercontent.com/97018228/216567538-8219a05f-1be0-476e-a804-91f372e7ed90.png">

**Comment by DarrenWestwood** [comment]
Fixed in https://github.com/blockonomics/prestashop-plugin/pull/158
