### ISSUE TITLE
Change Payment Status in Prestashop?

### ISSUE THREAD

**Issue by cryptojake** [blockonomics/prestashop-plugin#16]
After 1-3 payment confirmations is it possible to have the order status automatically change within Prestashop to "Payment Accepted" or something similar so the buyer knows? Otherwise it looks like I have to manually make the change the status within the order.

**Comment by shivaenigma** [comment]
This is already happening. Orders will move to Payment Accepted after 2 confirmations
![screenshot from 2017-03-29 10-34-34](https://cloud.githubusercontent.com/assets/737092/24439373/6c3ca9f4-146b-11e7-8104-4a883d65f958.png)

Is this not happening for you ?

**Comment by cryptojake** [comment]
Thats what I thought would happen, but it doesnt work in my shop (prestashop 1.6). Anything I could do to fix it?

**Comment by shivaenigma** [comment]
Are you able to see something like https://medias3.prestastore.com/817111-pbig/blockonomics-bitcoin-payments.jpg on zero confirmation ?

**Comment by cryptojake** [comment]
Unfortunately no. After payment and multiple confirms it never leaves the original page waiting for payment. The page does seem to reload every so often. If it helps, I downloaded the module directly from your website, not from the prestashop module store. Not sure if there is a difference.

**Comment by blockonomics** [comment]
This is exactly what is causing no change in payment status for you. This problem is explained in the README. The callback from blockonomics would update the status

> Order page repeatedly refreshing on payment: Your webhost is blocking incoming callbacks from bots, our you have a DDOS protection in place that is causing this. Blockonomics.co uses curl to callback your server with payment notification and cannot emulate a browser accessing your website.

If you can send an email to webmaster at blockonomics.co, will send you a slack request to our channel. Then our support engineer can help you fix the issue.

**Comment by cryptojake** [comment]
I will do that, thank you very much!

I have been using Bitpay for the last two years, but I like your module BETTER! The big difference I see is once someone places an order for bitcoin with Blockonomics it records the order even if payment has not arrived. With Bitpay, an order is never created unless bitcoin is sent. I appreciate your module much more because of your feature. A consumer does not have to go through all of the steps again to shop in the store if something happens to their browser or bitcoin wallet or whatever.

**Comment by blockonomics** [comment]
Closing. Was due to hosting server blocking callbacks due to user agent. @cryptojake  Let me know if you want to reopen
