### ISSUE TITLE
Improvement request - Blank table in invoices

### ISSUE THREAD

**Issue by noeldum** [blockonomics/prestashop-plugin#19]
It would be nice not to have any mention about bitcoin in the invoice if bitcoin has not been used as payment option.

Currently it shows a blank table with "Bitcoins Payed". Could that table go away unless bitcoin is used?

**Comment by blockonomics** [comment]
Thank you for pointing  this out. Will be taken up on priority

**Comment by shivaenigma** [comment]
Tracking in #24
