### ISSUE TITLE
Refactor 1.6 code

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#21]
- Move code out of paymentReturn hook
- Show payment screen in validation.php front end controller
- Remove unnecessary code and files
- Simplify the html payment template, directly redirect to order confirmation on websocket payment, no need to show unconfirmed/confirmed status with txid

For reference see https://github.com/blockonomics/prestashop-plugin/commits/1.7

**Comment by shivaenigma** [comment]
Done
