### ISSUE TITLE
Way to switch payment method after order created

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#27]
- Some users accidentally/out of curiosity click on pay with bitcoin
- After that they cannot switch to other modes of payment as shopping cart is lost

**Comment by shivaenigma** [comment]
- Order cannot be deleted while shopping cart can be deleted
- Retain cart and convert only to order when payment is done

**Comment by damontricomi** [comment]
Im lost please help me u can call me. Please give me a call 9728259305

**Comment by blockonomics** [comment]
Check how other payment methods are working

**Comment by blockonomics** [comment]
- The plugin should operate using only cart
- Cart should converted to order only when payment is done

**Comment by DarrenWestwood** [comment]
**Info on possible solutions**

https://www.prestashop.com/forums/topic/465587-prestashop-how-to-clear-cart-only-after-successful-payment/

Good insights from Paul C:
https://www.prestashop.com/forums/topic/5329-how-does-paymentprovider-validateorder-work/

Only run validateOrder from callback.php:
https://stackoverflow.com/questions/31827422/issue-with-creating-an-intermediate-pending-order/31913505

Duplicate the cart before validateOrder called:
https://www.knowband.com/blog/prestashop-tutorials/copy-cart-another-cart-order-change-id_cart/
https://stackoverflow.com/questions/41170756/how-to-call-function-after-payment-in-prestashop

Create an invoice for the order:
https://magento.stackexchange.com/questions/112935/how-to-create-unpaid-invoice-programmatically

**Comment by DarrenWestwood** [comment]
**Info on possible solutions**

https://www.prestashop.com/forums/topic/465587-prestashop-how-to-clear-cart-only-after-successful-payment/

Good insights from Paul C:
https://www.prestashop.com/forums/topic/5329-how-does-paymentprovider-validateorder-work/

Only run validateOrder from callback.php:
https://stackoverflow.com/questions/31827422/issue-with-creating-an-intermediate-pending-order/31913505

Duplicate the cart before validateOrder called:
https://www.knowband.com/blog/prestashop-tutorials/copy-cart-another-cart-order-change-id_cart/
https://stackoverflow.com/questions/41170756/how-to-call-function-after-payment-in-prestashop
