### ISSUE TITLE
Make compatible with PS  smart cache

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/prestashop-plugin#29]
If Smart cache for JavaScript in enabled from Advanced Parameters ==> Performances, the module frontend doesn't work properly.

This is due to angular / bootstrap JS files not getting properly loaded. [Refrence](https://www.prestashop.com/forums/topic/570036-free-modulebitcoin-payments-blockonomics/?p=2598537)

Find a way to fix

**Comment by blockonomics** [comment]
Verified on master. Working
