### ISSUE TITLE
nothing loads on validation page after clicking pay with bitcoin button

### ISSUE THREAD

**Issue by giallofanatic** [blockonomics/prestashop-plugin#33]
HI installed the module fine on prestashop 1.6 but on clicking the pay with bitcoin button on checkout
it loads the page xxxx/module/blockonomics/validation
but nothing happens, just an empty page except for the website headers and footers. There is nothing there for the customer to make payment
In the backend it records the order as awaiting payment but obviously no payment can be made.
Any help would be appreciated.
Thanks

**Comment by blockonomics** [comment]
Hi @giallofanatic . Thanks a lot for trying out our prestashop module. Can you temporarily enable our module on your store, so that we can debug the issue.

Also let me know your emailid,  I can invite you to our slack channel, where we can coordinate to fix this faster

**Comment by giallofanatic** [comment]
Hi thanks for the reply, my email is giallofanatic@gmail.com I will enable the module again.

Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&utm_medium=email&utm_campaign=sent-from-mailbird]
On 20/10/2017 06:10:46, Blockonomics <notifications@github.com> wrote:
Hi @giallofanatic [https://github.com/giallofanatic] . Thanks a lot for trying out our prestashop module. Can you temporarily enable our module on your store, so that we can debug the issue.
Also let me know your emailid, I can invite you to our slack channel, where we can coordinate to fix this faster

**Comment by blockonomics** [comment]
Was a problem with theme. Fixed
