### ISSUE TITLE
Size of bitcoin icon on PS 1.6 very big

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#34]
- On checkout size of icon very big

**Comment by damontricomi** [comment]
Hi was hoping all could help me . would like to spend some of my bitcoin
could u tell me how. Not sure.. Also i copied my private key to wallet but
it is not showing up in the app. Maybe we could set up an appointment

**Comment by blockonomics** [comment]
hi @damontricomi  please log a support ticket on https://blockonomics.freshdesk.com

**Comment by damontricomi** [comment]
U mean screen shot?

**Comment by blockonomics** [comment]
Yes, Please create new ticket using https://blockonomics.freshdesk.com/support/tickets/new and attach a screenshot

**Comment by damontricomi** [comment]
Did all get the email
