### ISSUE TITLE
PHP 7.0 on release 1.6.4 does not work

### ISSUE THREAD

**Issue by jusasiiv** [blockonomics/prestashop-plugin#36]
When using PHP 7.0 and plugin version 1.6.4 on Prestashop installation 1.6.1.17 the validation controller _controllers/front/validation.php_ does not work as intended. 

The order is correctly placed in the database in _blockonomics_bitcoin_orders_ and order is correctly generated in Prestashop, but the payment template does not load. Instead of showing payment information, the page redirects to _order.php?step=1_ and as the order has been placed, shows a message about the cart being empty. Downgrading to PHP 5.6 fixed the problem.

**Comment by blockonomics** [comment]
Can you confirm this on PS 1.7 as well

**Comment by jusasiiv** [comment]
PS 1.7 with PHP 7.0 works fine, no problem there

**Comment by jusasiiv** [comment]
I made a fresh install using PS 1.6.1.17 / PHP 7.0 / plugin version 1.6.4 and it works without a problem. The issue reported must have been some kind of conflict with the PS installation/plugins/server config and I am not being able to reproduce it on my local installation.

**Comment by blockonomics** [comment]
Thanks. Closing
