### ISSUE TITLE
prestashop 1.5.6

### ISSUE THREAD

**Issue by moran21** [blockonomics/prestashop-plugin#5]
uploaded on version of prestashop 1.5.6
exist on module page and payment gateways but not exist when customers try to pay
when tray to reset the module i get error 

[PrestaShopException]

Property Configuration->name length (33) must be between 0 and 32
at line 837 in file classes/ObjectModel.php

831. 
832. 			$message = $this->validateField($field, $this->$field);
833. 			if ($message !== true)
834. 			{
835. 				if ($die)
836. 					throw new PrestaShopException($message);
837. 				return $error_return ? $message : false;
838. 			}
839. 		}
840. 
841. 		return true;

    ObjectModelCore->validateFields - [line 255 - classes/ObjectModel.php] - [0 Argument]
    ObjectModelCore->getFields - [line 455 - classes/ObjectModel.php] - [0 Argument]
    ObjectModelCore->add - [line 360 - classes/Configuration.php] - [2 Arguments]
    ConfigurationCore::updateValue - [line 91 - modules/blockonomics/blockonomics.php] - [2 Arguments]
    Blockonomics->installOrder - [line 41 - modules/blockonomics/blockonomics.php] - [3 Arguments]
    Blockonomics->install - [line 498 - controllers/admin/AdminModulesController.php] - [0 Argument]
    AdminModulesControllerCore->postProcessReset - [line 806 - controllers/admin/AdminModulesController.php] - [0 Argument]
    AdminModulesControllerCore->postProcess - [line 158 - classes/controller/Controller.php] - [0 Argument]
    ControllerCore->run - [line 348 - classes/Dispatcher.php] - [0 Argument]
    DispatcherCore->dispatch - [line 53 - stor/index.php] - [0 Argument]

**Comment by cnu1439** [comment]
One of the order status id's length is more than 32. we will shorten the ids and update the code. Thanks for reporting this bug.

**Comment by cnu1439** [comment]
https://github.com/blockonomics/prestashop-plugin/commit/acb5df8ed66ce90208ce860e5b0a01d303121bed

**Comment by blockonomics** [comment]
@moran21 please confirm if its confirm for you now
