### ISSUE TITLE
Arrow on refund page is confusing

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/prestashop-plugin#59]
![screenshot from 2019-03-01 20-01-26](https://user-images.githubusercontent.com/737092/53644530-d170d000-3c5c-11e9-9b6a-8765019161a3.png)

Arrow is not clickable and doesn't rotate. It is not clear from the UI that page auto refershes

**Comment by DarrenWestwood** [comment]
Closing issue as this has been deprecated.
