### ISSUE TITLE
addr varchar(255) is causing issue

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#69]
On some hosts due to this it is unable to create database table
https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

Solution is to decrease length of addr field in table .Make sure bech32 address fits in

**Comment by DarrenWestwood** [comment]
InnoDB has a maximum index length of 767 bytes, so with utf8mb4 you can only store **191 characters**.
Bech32 string is at most **90 characters**.

Decreased `varchar(255)` to max allowable `varchar(191)`.
Alters database for upgrading users.
