### ISSUE TITLE
Temp fund wallet

### ISSUE THREAD

**Issue by blockonomics** [blockonomics/prestashop-plugin#75]
Find out if this is possible to achieve (no need to code yet):
- If user clicks on Install and doesn't configure .. can we make it sure temp wallet like Wordpress

**Comment by DarrenWestwood** [comment]
In woocommerce we create the temp wallet while creating the settings page, after generating the secret:
https://github.com/blockonomics/woocommerce-plugin/blob/master/blockonomics-woocommerce.php#L115

We can add the same functionality, as we generate the secret during the plugin db installation:
https://github.com/blockonomics/prestashop-plugin/blob/altcoin_presta_1.7/blockonomics.php#L179

**Comment by blockonomics** [comment]
Can you verify when installDB() will be called, in these cases
- If user installs the plugin but doesn't click on configure
- User clicks on configure but doesn't change/save any settings

**Comment by DarrenWestwood** [comment]
`installDB()` runs when the plugin is installed before clicking on configure.

**Comment by blockonomics** [comment]
Ok Lets start with work on implementing this
