### ISSUE TITLE
Some Translation strings are not correct [PS 1.7]

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/prestashop-plugin#89]
![6006dd85b7ccc](https://user-images.githubusercontent.com/737092/108210831-092af800-7152-11eb-9770-af38dfe727f1.png)

It would be also wise to check all translation strings once

**Comment by shivaenigma** [comment]
Revisit code to see all translation strings are correct

**Comment by cnohall** [comment]
Sounds good, always good to check translation strings after updates to make sure that they are correct.

**Comment by cnohall** [comment]
The example shown above seems to be from a previous version of the module. The current version shows this.
![translation](https://user-images.githubusercontent.com/36883813/111282991-f12b9300-8681-11eb-89e7-ca94d14d99a2.png)

I'll still test and check so that all the strings are available for translation in the current version.

**Comment by cnohall** [comment]
There's a string called _testSetup_ that should probably be removed or updated.
![image](https://user-images.githubusercontent.com/36883813/111291639-bbd77300-868a-11eb-8a62-1cc624a9cc93.png)

**Comment by cnohall** [comment]
_Order_ does not seem to be set by the Blockonomics module. 
![image](https://user-images.githubusercontent.com/36883813/111296098-6fdafd00-868f-11eb-94ed-cd681dbc7fae.png)

**Comment by cnohall** [comment]
Storing what needs to be done in [this spreedsheet](https://docs.google.com/spreadsheets/d/1F8Tkp_uXLa6bKBKZlYYtsWNDigkzn9vBiAhqWR8hI-Y/edit#gid=1386834576).

**Comment by cnohall** [comment]
Fixed the main things within this issue. I also added a Swedish translation (used it for the testing too). I will move on to the issues with higher priority.

**Comment by cnohall** [comment]
I've now checked all the strings and made sure that they are translatable.
