### ISSUE TITLE
Implementation for PS [1.7]

### ISSUE THREAD

**Issue by numanWD** [blockonomics/prestashop-plugin#9]
In PS 1.7 there is a new `hook` for the payments modules. It is called `paymentOptions`.

**Comment by shivaenigma** [comment]
Can you provide some details on what errors you are getting on PS 1.7

**Comment by numanWD** [comment]
Hi,

The `hook` `payment` has to be renamed `paymentOptions`.

You can find a reference is the prestahop payment example.

https://github.com/PrestaShop/paymentexample/blob/master/paymentexample.php


Let me know if you need some help.

Thanks

**Comment by shivaenigma** [comment]
thanks @numanWD 
Can you explain how to retain backward compatibility for 1.6 with the same code base ? 
Or is it necessary to create a new branch

**Comment by numanWD** [comment]
Hi @shivaenigma 
I will create a second branch or repo for 1.7.

> Modules built for PrestaShop 1.6 will mostly still work with 1.7 (apart from payment modules, which have seen an small API change – see two sections below). Their presentation code will probably have to be reworked (to different extents depending on the module) in order to look good.

http://build.prestashop.com/news/prestashop-1-7-faq/#will-16-modules-still-work-with-prestashop-17

**Comment by shivaenigma** [comment]
@numanWD 
Please to announce our first version for PS 1.7 https://github.com/blockonomics/prestashop-plugin/releases/tag/1.7.1
Feel free to test and let me know feedback

**Comment by blockonomics** [comment]
PS 1.7 support has been released. Closing this
