### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/prestashop-plugin#91]
- Hostname in callback URL is not updated after [changing hostname in PS](https://drive.google.com/file/d/1Z2gcAL4YTc247vBrJEmE3s9VX1DNRkhp/view): Callback URL should never be saved in DB. Should always be generated dynamically from stored secret and current host
- **Secret not matching** and **Callbacks from incorrect address**  in callback should show correct error
- Careers and Shipping: Have a relook at this. I am not sure why we are creating a new carrier called *blockonomics_ps*. We want our payment method to be enabled for all shipping zones 
- Regeneration of callback URL with secret: Lets explore possible UI .. should not cause lot of hassle or workarounds - low priority

**Comment by cnohall** [comment]
I'll tackle one minor issue at a time and keep _this issue_ updated about the progress.

**Comment by cnohall** [comment]
Fixed: Secret not matching and Callbacks from incorrect address in callback should show correct error.

**Comment by cnohall** [comment]
Fixed so that HTTP CALLBACK URL is generated dynamically from stored secret and current host.

**Comment by cnohall** [comment]
I looked into _Careers and Shipping_. We aren't creating a carrier called _blockonomics_ps_. This was just what I choose to call my store. PrestaShop automatically created the Carrier called the same name as the shop. Hence, we don't need to make any changes, since we aren't touching the carriers and shipping to begin with.

**Comment by cnohall** [comment]
Regarding _Regeneration of callback URL with secret_:

How about adding a button like on the screenshot below? I also changed the look of the test setup button, before it looked the same as the _save_ button.

![image](https://user-images.githubusercontent.com/36883813/112743704-90328200-8fd4-11eb-8f8d-0ecae641811d.png)

Let me know what you think.
