### ISSUE TITLE
Address Reuse is not happening

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/prestashop-plugin#92]
@DarrenWestwood  will briefly write the design or summary for implementing this

It is important to note that we have implemented a cart duplication logic in https://github.com/blockonomics/prestashop-plugin/issues/27

**Comment by cnohall** [comment]
Good that we have logic for this already. I'll go through it and turn to Darren if I get stuck. This is quite important, since it saves the database and server from a new order after each refresh.

**Comment by DarrenWestwood** [comment]
The duplicated cart_id is saved to the [user cookie](https://github.com/blockonomics/prestashop-plugin/blob/1.7/controllers/front/validation.php#L177) and to [blockonomics_orders](https://github.com/blockonomics/prestashop-plugin/blob/1.7/controllers/front/validation.php#L183).
During the checkout process, before creating a new address, we should check for an existing blockonomics_orders, with the same cart_id:
https://github.com/blockonomics/prestashop-plugin/blob/1.7/controllers/front/validation.php#L101

The [new address](https://github.com/blockonomics/prestashop-plugin/blob/1.7/controllers/front/validation.php#L101), [cart duplication](https://github.com/blockonomics/prestashop-plugin/blob/1.7/controllers/front/validation.php#L122), and [order validation](https://github.com/blockonomics/prestashop-plugin/blob/1.7/controllers/front/validation.php#L161) should only run if there is not an existing order already.

**Comment by shivaenigma** [comment]
When payment page is refershed, it is causing multiple carts (This should not happen)
![60531859efda4](https://user-images.githubusercontent.com/737092/111978566-0bee8380-8b2a-11eb-9b20-bd40f39105a4.png)

**Comment by cnohall** [comment]
@DarrenWestwood

In answer to:
_The duplicated cart_id is saved to the user cookie and to blockonomics_orders.
During the checkout process, before creating a new address, we should check for an existing blockonomics_orders, with the same cart_id:
https://github.com/blockonomics/prestashop-plugin/blob/1.7/controllers/front/validation.php#L101

The new address, cart duplication, and order validation should only run if there is not an existing order already._

May I ask for some clarification? For example, when I've looked in blockonomics_orders. There is no cart_id, however there is a id_cart. Is cart_id and id_cart the same in this case?

Also, when I remove order validation out of the equation (for when the order with the same id_cart exists) the order doesn't refresh with a qr code, or anything else out of the checkout screen, except the order number. Any tips on where I should look would be appreciated.

**Comment by DarrenWestwood** [comment]
> There is no cart_id, however there is a id_cart. Is cart_id and id_cart the same in this case?

Yes, id_cart should be checked for an existing order.

> Also, sometimes the blockonomics id_cart is out of sync with the prestashop id_cart.

The id_cart may differ from the prestashop id_cart due to [creating a new cart during checkout](https://github.com/blockonomics/prestashop-plugin/blob/1.7/controllers/front/validation.php#L173-L180) (Allows the user to click back and try a different payment provider). The new id_cart is saved in blockonomics_orders and set to the cookie. When refreshing or going back and trying again the id_cart can be checked against the saved new id_cart in order to return an existing_order.

**Comment by cnohall** [comment]
Thanks for the help, now it's in a working condition. Just have one question. If someone returns to the shop and adds products to the cart, do we want to update the current order or do we want to create a new order?

I'll move on to the timer issue in the meantime

**Comment by DarrenWestwood** [comment]
We should create a new order to ensure a user cannot change the order fiat total from the checkout end. This may lead to incorrect totals in the order if the order is changed after a payment has been made.

**Comment by cnohall** [comment]
Sounds good. I'll make it so that a new order is created in that case.
