### ISSUE TITLE
Refresh Payment Page Timer

### ISSUE THREAD

**Issue by shivaenigma** [blockonomics/prestashop-plugin#93]
- Timer should resume from last seen time
- Use remaining time to avoid [payment expired early issues](https://github.com/blockonomics/woocommerce-plugin/issues/191)

Again @DarrenWestwood  can comment more on this

**Comment by cnohall** [comment]
Looking forward to Darren's comments, also I'm glad that we have code regarding this. I'll examine the previous code to keep the updates in line with the standard we are already using.

**Comment by DarrenWestwood** [comment]
This should be based on the changes in issue #92, as this will make an existing orders information available. 

The current timestamp is currently [saved to the blockonomics_order](https://github.com/blockonomics/prestashop-plugin/blob/master/controllers/front/validation.php#L97) and can be used for the payment timer calculation:
https://github.com/blockonomics/woocommerce-plugin/pull/201/files#diff-a3307e680eb76b9d93556c9ae2e5dc134b3526246480730fb8ddf49186da29ebR410.

It will also be required to check the time_remaining for an existing order and update the order timestamp and price if expired:
https://github.com/blockonomics/woocommerce-plugin/blob/master/php/Blockonomics.php#L400

**Comment by cnohall** [comment]
I'm more or less done with this issue now. Just have a question about this:

> It will also be required to check the time_remaining for an existing order and update the order _timestamp_ and _price_ if expired:
> https://github.com/blockonomics/woocommerce-plugin/blob/master/php/Blockonomics.php#L400

Isn't it ok to keep the timestamp and price as is? If not what should it be changed to?

**Comment by DarrenWestwood** [comment]
The timestamp should be updated with the new timestamp `time()` if an order is expired. This is required to ensure the time_remaining is reset when the user refreshes the page or goes back and tries again after an order has expired:
https://github.com/blockonomics/woocommerce-plugin/pull/201/files#diff-a3307e680eb76b9d93556c9ae2e5dc134b3526246480730fb8ddf49186da29ebR410

The main function of the countdown timer is to lock the bitcoin price for the set period. After the set period the user should still be able to try making the payment again, however, they should receive a new bitcoin price to calculate the expected bitcoin amount. This ensures a user cannot open an order, wait for a change in the exchange rate and then fulfill the order for a lesser amount.

**Comment by cnohall** [comment]
Thanks for your explanation. It clarified it, so that I know how to structure the code to handle those cases.
