### ISSUE TITLE
Prestashop > 1.7.7.2 Compatibility

### ISSUE THREAD

**Issue by DarrenWestwood** [blockonomics/prestashop-plugin#99]
Confirmed payment callbacks are failing with the following error.
![127-0-0-1-prestashop3-modules-blockonomics-callback-php-secret-083618744da1824f9806d02fec94c25a-addr-bc1q97y24fkm9w4rqzgaa7dp62ep956j27ewhgdr0p-status-2-txid-WarningThisIsAGeneratedTestPaymentAndNotARealBitcoinTransaction-value-82073](https://user-images.githubusercontent.com/39666372/113295768-e6ffca80-92f8-11eb-9e01-ca35e3beb50a.png)

`$o->setCurrentState(Configuration::get('PS_OS_PAYMENT'));` is causing the issue. This should be looked into what is causing this error.

A temporary fix is to directly change the status in the database `Db::getInstance()->execute('UPDATE '._DB_PREFIX_.'orders SET current_state = 2 WHERE id_cart = '.$o->id_cart)`. This works but does not send email, trigger post payment hooks etc.

**Comment by DarrenWestwood** [comment]
@cnohall, please look into this issue to see what is causing it, if other modules have the same issue, and if there is a better solution than updating the status in the database.

As a starting point, a similar issue has been reported here: 
https://github.com/PrestaShop/PrestaShop/issues/20029. 
Check if the fix in the PR can be used to fix this error in our module:
https://github.com/PrestaShop/PrestaShop/pull/18859/files

**Comment by cnohall** [comment]
I've tried to recreate the error. However, when I try, the confirmation callback seems to work as it should. 
![image](https://user-images.githubusercontent.com/36883813/113366899-7d81c980-9395-11eb-9f39-2d41a9aed15d.png)

I used both localhost and ngrok, with the confirmation callback appearing to work in both cases. Perhaps I'm missing something in my testing?

**Comment by DarrenWestwood** [comment]
You are correct, the payment is marked as paid, however, the request will respond with HTTP status 500. Enable debugging mode and manually open the callback request in your browser. eg.
http://yoururl.com/prestashop/modules/blockonomics/callback.php?secret=c3d959b9f86637cc98267f84df95d34f&addr=bc1qxunt0jdanahvup03tlln0jgwaedd9ju5zfdszd&status=2&txid=WarningThisIsAGeneratedTestPaymentAndNotARealBitcoinTransaction&value=146843

**Comment by cnohall** [comment]
It works if we define 
```
Context::getContext()->currency = new \stdClass;
Context::getContext()->currency->precision = 0;
```
before running `$o->setCurrentState(Configuration::get('PS_OS_PAYMENT'));`.

**Comment by cnohall** [comment]
Adding `Context::getContext()->currency = Context::getContext()->currency ?? new Currency (Configuration::get ('PS_CURRENCY_DEFAULT'));`

On the line before `$o->setCurrentState(Configuration::get('PS_OS_PAYMENT'));` is enough to get it to work. I've created a PR.
